### ISSUE TITLE
type stability

### ISSUE THREAD

**Issue by gvdr** [jrhut/Longurl.jl#1]
Great Work @jrhut 

Couple of little things:

- [ ] it may be worth to define `expand_urls()` as type stable function: it gets an array of strings as input, and it return array of strings.
    Motivation: we can drop the dependencies on `DataFrames` and support a wider variety of use cases.

    Mock implementation:

    ```julia
    function expand_urls(urls_to_expand, seconds=2)
        ...
        long_urls = [expanded_url=expanded_urls, status_code=status_codes]

    return long_urls
    ```

If we had to reproduce the functionality of the current version of the function, we would do something like:

```julia
using Longurl
using DataFrames

my_short_url = ["https://tinyurl.com/yfr3dtha"]
my_long_url = expand_urls(my_short_url)

my_url_df = DataFrame(shorts = my_short_url, longs = my_long_url.expanded_url, status = my_long_url.status_code)
```

**Comment by jrhut** [comment]
I like this idea! So I've gone ahead and replaced the DataFrame return with data structure containing the expanded_url and status_code properties as arrays.

**Comment by gvdr** [comment]
great!
